version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosec
    - gocritic
    - revive
  exclusions:
    rules:
      - linters:
          - revive
        text: "stutters"

issues:
  max-issues-per-linter: 100
  max-same-issues: 50
