// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfFile returns the embedded CollectionSpec for BpfFile.
func LoadBpfFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfFileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfFile: %w", err)
	}

	return spec, err
}

// LoadBpfFileObjects loads BpfFile and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfFileObjects
//	*BpfFilePrograms
//	*BpfFileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfFileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfFileSpecs struct {
	BpfFileProgramSpecs
	BpfFileMapSpecs
	BpfFileVariableSpecs
}

// BpfFileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfFileProgramSpecs struct {
	TraceOpenat *ebpf.ProgramSpec `ebpf:"trace_openat"`
}

// BpfFileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfFileMapSpecs struct {
	FileAccessTotal *ebpf.MapSpec `ebpf:"file_access_total"`
}

// BpfFileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfFileVariableSpecs struct {
}

// BpfFileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfFileObjects struct {
	BpfFilePrograms
	BpfFileMaps
	BpfFileVariables
}

func (o *BpfFileObjects) Close() error {
	return _BpfFileClose(
		&o.BpfFilePrograms,
		&o.BpfFileMaps,
	)
}

// BpfFileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfFileMaps struct {
	FileAccessTotal *ebpf.Map `ebpf:"file_access_total"`
}

func (m *BpfFileMaps) Close() error {
	return _BpfFileClose(
		m.FileAccessTotal,
	)
}

// BpfFileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfFileVariables struct {
}

// BpfFilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfFilePrograms struct {
	TraceOpenat *ebpf.Program `ebpf:"trace_openat"`
}

func (p *BpfFilePrograms) Close() error {
	return _BpfFileClose(
		p.TraceOpenat,
	)
}

func _BpfFileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpffile_bpf.o
var _BpfFileBytes []byte
