// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfKernel returns the embedded CollectionSpec for BpfKernel.
func LoadBpfKernel() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfKernelBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfKernel: %w", err)
	}

	return spec, err
}

// LoadBpfKernelObjects loads BpfKernel and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfKernelObjects
//	*BpfKernelPrograms
//	*BpfKernelMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfKernelObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfKernel()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfKernelSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfKernelSpecs struct {
	BpfKernelProgramSpecs
	BpfKernelMapSpecs
	BpfKernelVariableSpecs
}

// BpfKernelProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfKernelProgramSpecs struct {
	TraceFinitModule *ebpf.ProgramSpec `ebpf:"trace_finit_module"`
	TraceInitModule  *ebpf.ProgramSpec `ebpf:"trace_init_module"`
}

// BpfKernelMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfKernelMapSpecs struct {
	ModuleLoadTotal *ebpf.MapSpec `ebpf:"module_load_total"`
}

// BpfKernelVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfKernelVariableSpecs struct {
}

// BpfKernelObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfKernelObjects struct {
	BpfKernelPrograms
	BpfKernelMaps
	BpfKernelVariables
}

func (o *BpfKernelObjects) Close() error {
	return _BpfKernelClose(
		&o.BpfKernelPrograms,
		&o.BpfKernelMaps,
	)
}

// BpfKernelMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfKernelMaps struct {
	ModuleLoadTotal *ebpf.Map `ebpf:"module_load_total"`
}

func (m *BpfKernelMaps) Close() error {
	return _BpfKernelClose(
		m.ModuleLoadTotal,
	)
}

// BpfKernelVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfKernelVariables struct {
}

// BpfKernelPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfKernelObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfKernelPrograms struct {
	TraceFinitModule *ebpf.Program `ebpf:"trace_finit_module"`
	TraceInitModule  *ebpf.Program `ebpf:"trace_init_module"`
}

func (p *BpfKernelPrograms) Close() error {
	return _BpfKernelClose(
		p.TraceFinitModule,
		p.TraceInitModule,
	)
}

func _BpfKernelClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfkernel_bpf.o
var _BpfKernelBytes []byte
