// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfNetwork returns the embedded CollectionSpec for BpfNetwork.
func LoadBpfNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfNetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfNetwork: %w", err)
	}

	return spec, err
}

// LoadBpfNetworkObjects loads BpfNetwork and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfNetworkObjects
//	*BpfNetworkPrograms
//	*BpfNetworkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfNetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfNetworkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfNetworkSpecs struct {
	BpfNetworkProgramSpecs
	BpfNetworkMapSpecs
	BpfNetworkVariableSpecs
}

// BpfNetworkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfNetworkProgramSpecs struct {
	TraceTcpStateChange *ebpf.ProgramSpec `ebpf:"trace_tcp_state_change"`
}

// BpfNetworkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfNetworkMapSpecs struct {
	ConnectActive     *ebpf.MapSpec `ebpf:"connect_active"`
	ConnectErrorTotal *ebpf.MapSpec `ebpf:"connect_error_total"`
	ConnectTotal      *ebpf.MapSpec `ebpf:"connect_total"`
}

// BpfNetworkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfNetworkVariableSpecs struct {
}

// BpfNetworkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfNetworkObjects struct {
	BpfNetworkPrograms
	BpfNetworkMaps
	BpfNetworkVariables
}

func (o *BpfNetworkObjects) Close() error {
	return _BpfNetworkClose(
		&o.BpfNetworkPrograms,
		&o.BpfNetworkMaps,
	)
}

// BpfNetworkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfNetworkMaps struct {
	ConnectActive     *ebpf.Map `ebpf:"connect_active"`
	ConnectErrorTotal *ebpf.Map `ebpf:"connect_error_total"`
	ConnectTotal      *ebpf.Map `ebpf:"connect_total"`
}

func (m *BpfNetworkMaps) Close() error {
	return _BpfNetworkClose(
		m.ConnectActive,
		m.ConnectErrorTotal,
		m.ConnectTotal,
	)
}

// BpfNetworkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfNetworkVariables struct {
}

// BpfNetworkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfNetworkPrograms struct {
	TraceTcpStateChange *ebpf.Program `ebpf:"trace_tcp_state_change"`
}

func (p *BpfNetworkPrograms) Close() error {
	return _BpfNetworkClose(
		p.TraceTcpStateChange,
	)
}

func _BpfNetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfnetwork_bpf.o
var _BpfNetworkBytes []byte
