// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfPrivilege returns the embedded CollectionSpec for BpfPrivilege.
func LoadBpfPrivilege() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfPrivilegeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfPrivilege: %w", err)
	}

	return spec, err
}

// LoadBpfPrivilegeObjects loads BpfPrivilege and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfPrivilegeObjects
//	*BpfPrivilegePrograms
//	*BpfPrivilegeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfPrivilegeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfPrivilege()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfPrivilegeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPrivilegeSpecs struct {
	BpfPrivilegeProgramSpecs
	BpfPrivilegeMapSpecs
	BpfPrivilegeVariableSpecs
}

// BpfPrivilegeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPrivilegeProgramSpecs struct {
	TraceCapsetEnter *ebpf.ProgramSpec `ebpf:"trace_capset_enter"`
	TraceCapsetExit  *ebpf.ProgramSpec `ebpf:"trace_capset_exit"`
	TraceSetgidEnter *ebpf.ProgramSpec `ebpf:"trace_setgid_enter"`
	TraceSetgidExit  *ebpf.ProgramSpec `ebpf:"trace_setgid_exit"`
	TraceSetuidEnter *ebpf.ProgramSpec `ebpf:"trace_setuid_enter"`
	TraceSetuidExit  *ebpf.ProgramSpec `ebpf:"trace_setuid_exit"`
}

// BpfPrivilegeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPrivilegeMapSpecs struct {
	CallTypeTmp              *ebpf.MapSpec `ebpf:"call_type_tmp"`
	PrivilegeEscalationTotal *ebpf.MapSpec `ebpf:"privilege_escalation_total"`
}

// BpfPrivilegeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfPrivilegeVariableSpecs struct {
}

// BpfPrivilegeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrivilegeObjects struct {
	BpfPrivilegePrograms
	BpfPrivilegeMaps
	BpfPrivilegeVariables
}

func (o *BpfPrivilegeObjects) Close() error {
	return _BpfPrivilegeClose(
		&o.BpfPrivilegePrograms,
		&o.BpfPrivilegeMaps,
	)
}

// BpfPrivilegeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrivilegeMaps struct {
	CallTypeTmp              *ebpf.Map `ebpf:"call_type_tmp"`
	PrivilegeEscalationTotal *ebpf.Map `ebpf:"privilege_escalation_total"`
}

func (m *BpfPrivilegeMaps) Close() error {
	return _BpfPrivilegeClose(
		m.CallTypeTmp,
		m.PrivilegeEscalationTotal,
	)
}

// BpfPrivilegeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrivilegeVariables struct {
}

// BpfPrivilegePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfPrivilegeObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrivilegePrograms struct {
	TraceCapsetEnter *ebpf.Program `ebpf:"trace_capset_enter"`
	TraceCapsetExit  *ebpf.Program `ebpf:"trace_capset_exit"`
	TraceSetgidEnter *ebpf.Program `ebpf:"trace_setgid_enter"`
	TraceSetgidExit  *ebpf.Program `ebpf:"trace_setgid_exit"`
	TraceSetuidEnter *ebpf.Program `ebpf:"trace_setuid_enter"`
	TraceSetuidExit  *ebpf.Program `ebpf:"trace_setuid_exit"`
}

func (p *BpfPrivilegePrograms) Close() error {
	return _BpfPrivilegeClose(
		p.TraceCapsetEnter,
		p.TraceCapsetExit,
		p.TraceSetgidEnter,
		p.TraceSetgidExit,
		p.TraceSetuidEnter,
		p.TraceSetuidExit,
	)
}

func _BpfPrivilegeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfprivilege_bpf.o
var _BpfPrivilegeBytes []byte
