// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBpfProcess returns the embedded CollectionSpec for BpfProcess.
func LoadBpfProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BpfProcess: %w", err)
	}

	return spec, err
}

// LoadBpfProcessObjects loads BpfProcess and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfProcessObjects
//	*BpfProcessPrograms
//	*BpfProcessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpfProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfProcessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProcessSpecs struct {
	BpfProcessProgramSpecs
	BpfProcessMapSpecs
	BpfProcessVariableSpecs
}

// BpfProcessProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProcessProgramSpecs struct {
	TraceExecve      *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceProcessExit *ebpf.ProgramSpec `ebpf:"trace_process_exit"`
}

// BpfProcessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProcessMapSpecs struct {
	ActiveProcessCount *ebpf.MapSpec `ebpf:"active_process_count"`
	ConfigMap          *ebpf.MapSpec `ebpf:"config_map"`
	ExecCategoryCount  *ebpf.MapSpec `ebpf:"exec_category_count"`
	ExitCategoryCount  *ebpf.MapSpec `ebpf:"exit_category_count"`
	PidCategory        *ebpf.MapSpec `ebpf:"pid_category"`
}

// BpfProcessVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProcessVariableSpecs struct {
}

// BpfProcessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfProcessObjects struct {
	BpfProcessPrograms
	BpfProcessMaps
	BpfProcessVariables
}

func (o *BpfProcessObjects) Close() error {
	return _BpfProcessClose(
		&o.BpfProcessPrograms,
		&o.BpfProcessMaps,
	)
}

// BpfProcessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfProcessMaps struct {
	ActiveProcessCount *ebpf.Map `ebpf:"active_process_count"`
	ConfigMap          *ebpf.Map `ebpf:"config_map"`
	ExecCategoryCount  *ebpf.Map `ebpf:"exec_category_count"`
	ExitCategoryCount  *ebpf.Map `ebpf:"exit_category_count"`
	PidCategory        *ebpf.Map `ebpf:"pid_category"`
}

func (m *BpfProcessMaps) Close() error {
	return _BpfProcessClose(
		m.ActiveProcessCount,
		m.ConfigMap,
		m.ExecCategoryCount,
		m.ExitCategoryCount,
		m.PidCategory,
	)
}

// BpfProcessVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfProcessVariables struct {
}

// BpfProcessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfProcessPrograms struct {
	TraceExecve      *ebpf.Program `ebpf:"trace_execve"`
	TraceProcessExit *ebpf.Program `ebpf:"trace_process_exit"`
}

func (p *BpfProcessPrograms) Close() error {
	return _BpfProcessClose(
		p.TraceExecve,
		p.TraceProcessExit,
	)
}

func _BpfProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfprocess_bpf.o
var _BpfProcessBytes []byte
